version: '3.5'
services:
  redis:
    image: redis
    ports:
    - "6379:6379"
  worker:
    build:
      context: .
      dockerfile: Dockerfile
    image: madefire/chordtest
    command: ['celery', '-A', 'src.tasks', 'worker', '-l', 'info']
    environment:
      - BROKER_URL=redis://redis:6379/0 # para encolar
      - RESULT_BACKEND=redis://redis:6379/0 # para guardar el resultado
      - C_FORCE_ROOT=true
    volumes:
      - ./:/app/
    depends_on:
      - redis
  database:
      image: postgres:latest
      restart: always
      volumes:
        - database:/var/lib/postgresql/data
        - ./migrations:/docker-entrypoint-initdb.d
      environment:
        POSTGRES_PASSWORD: password
        POSTGRES_USER: user
        POSTGRES_DB: main
      ports:
        - 5432:5432
  minio:
      image: minio/minio:RELEASE.2021-07-22T05-23-32Z
      ports:
        - 9000:9000
        - 9001:9001
      volumes:
        - minio:/data
      command: server /data --console-address ":9001"

volumes:
  database:
  minio:
