version: '3.5'
services:
  redis:
    image: redis
    ports:
    - "6379:6379"
  # worker:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   command: ['celery', '-A', 'src.tasks', 'worker', '-l', 'info']
  #   environment:
  #     - BROKER_URL=redis://10.0.0.2:6379/0 # para encolar
  #     - RESULT_BACKEND=redis://10.0.0.2:6379/0 # para guardar el resultado
  #     - DATABASE_HOST=10.0.0.2:5432
  #     - MINIO_URL=10.0.0.2:9000
  #     - C_FORCE_ROOT=true
  #   volumes:
  #     - ./:/app/
  #   depends_on:
  #     - redis
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: ['gunicorn', '--bind', '0.0.0.0:5000', '-w', '4', '--pythonpath', 'src', 'src.app:app']
    environment:
      - BROKER_URL=redis://redis:6379/0 # para encolar
      - RESULT_BACKEND=redis://redis:6379/0 # para guardar el resultado
      - MINIO_URL=minio:9000
      - DATABASE_HOST=database:5432
    volumes:
      - ./:/app/
    depends_on:
      - redis
    ports:
      - 5000:5000
  database:
      image: postgres:latest
      restart: always
      volumes:
        - database:/var/lib/postgresql/data
        - ./migrations:/docker-entrypoint-initdb.d
      environment:
        POSTGRES_PASSWORD: password
        POSTGRES_USER: user
        POSTGRES_DB: main
      ports:
        - 5432:5432
  minio:
      image: minio/minio:RELEASE.2021-07-22T05-23-32Z
      ports:
        - 9000:9000
        - 9001:9001
      volumes:
        - ./minio_data:/data
      environment:
        - MINIO_ROOT_USER=minioadmin
        - MINIO_ROOT_PASSWORD=password
        - MINIO_STORAGE_USE_HTTPS=False
      command: server /data --console-address ":9001"

volumes:
  database:
